name: CI/CD Pipeline to Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Verificação
      uses: actions/checkout@v3

    - name: login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/trabalhorodrigo:latest .

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/trabalhorodrigo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y ssh

    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 201.23.3.86
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/trabalhorodrigo:latest
          docker stop trabalhorodrigo || true
          docker rm trabalhorodrigo || true
          docker run -d -p 8093:3000 --name trabalhorodrigo ${{ secrets.DOCKER_USERNAME }}/trabalhorodrigo:latest
